# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-demo-project',
                'doc_host': 'https://suri-kunal.github.io',
                'git_url': 'https://github.com/suri-kunal/nbdev-demo-project',
                'lib_path': 'nbdev_demo_project'},
  'syms': {'nbdev_demo_project.core': {'nbdev_demo_project.core.foo': ('core.html#foo', 'nbdev_demo_project/core.py')}}}
